# Generated by Django 3.2.20 on 2023-09-20 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_newslettter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Newslettter',
            new_name='Newsletter',
        ),
    ]
