# Generated by Django 3.2.20 on 2023-09-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_category'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_date'], name='blog_post_created_16bfbe_idx'),
        ),
    ]
