# Generated by Django 3.2.20 on 2023-09-20 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_blog_post_created_16bfbe_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='blog_post_created_16bfbe_idx',
        ),
    ]
