# Generated by Django 3.2.20 on 2023-09-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_newsletter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
